# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "mongoid_midgets"
  s.version = "0.0.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Christoph Grabo"]
  s.date = "2012-02-19"
  s.description = "mongoid_midgets is a meta/dependency gem for my microgems."
  s.email = "chris@dinarrr.com"
  s.extra_rdoc_files = [
    "README.md"
  ]
  s.files = [
    ".rvmrc",
    "Gemfile",
    "Gemfile.lock",
    "README.md",
    "Rakefile",
    "lib/mongoid_midgets.rb",
    "mongoid_midgets.gemspec"
  ]
  s.homepage = "http://github.com/asaaki/mongoid_midgets"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.15"
  s.summary = "meta/dependency gem for mongoid microgems"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<mongoid_bitfield>, [">= 0"])
      s.add_runtime_dependency(%q<mongoid_touch>, [">= 0"])
      s.add_runtime_dependency(%q<mongoid_upk>, [">= 0"])
      s.add_development_dependency(%q<rake>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
    else
      s.add_dependency(%q<mongoid_bitfield>, [">= 0"])
      s.add_dependency(%q<mongoid_touch>, [">= 0"])
      s.add_dependency(%q<mongoid_upk>, [">= 0"])
      s.add_dependency(%q<rake>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
    end
  else
    s.add_dependency(%q<mongoid_bitfield>, [">= 0"])
    s.add_dependency(%q<mongoid_touch>, [">= 0"])
    s.add_dependency(%q<mongoid_upk>, [">= 0"])
    s.add_dependency(%q<rake>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
  end
end

